apiVersion: v1
stringData:
  WALLET_PASSWORD: {{ .Values.wallet.password | quote }}
  WALLET_MNEMONIC: {{ .Values.wallet.mnemonic | quote }}
  WALLET_MNEMONIC_PASSPHRASE: {{ .Values.wallet.mnemonic_passphrase | quote }}
kind: Secret
metadata:
  name: mining-companion-secrets
  namespace: {{ .Release.Namespace | quote }}
type: Opaque